server:
  port: 7900
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/SunYshineC-M/config-demo.git #https://github.com/SundyYi/config.git
          username: glankspring@163.com
          password: jiedimei1995
          search-paths: configserver
  application:
    name: dm-spring-config-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@47.94.235.82:7776/eureka/
