server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@47.94.235.82:7776/eureka/
spring:
  datasource:
    # 使用druid数据源
    url: jdbc:mysql://localhost:3306/js_bank_account
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #最大连接池数量
      max-active: 10
      #最小连接池数量
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      #销毁线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于minEvictableIdleTimeMillis，则关闭当前连接。
      minEvictableIdleTimeMillis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validationQuery: select 'x'
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
  application:
    name: js-producer-remittance
  profiles:
    active: dev
  rabbitmq:
    host: 123.206.255.244
    port: 5672
    username: sundy
    password: sunyi
    virtual-host: /sundy-cm
    publisher-confirms: true
    publisher-returns: true
    listener:
        simple:
          prefetch: 1
#  redis: #Redis配置
#        database: 0 # Redis数据库索引（默认为0）
#        host: 127.0.0.1  #Redis服务器地址
#        port: 6379 # Redis服务器连接端口
#        password: # Redis服务器连接密码（默认为空）
#        pool:
#          max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
#          max-idle: 10 # 连接池中的最大空闲连接
#          max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          min-idle: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml