server:
  port: 8021
spring:
  application:
    name: js-consumer-management
  rabbitmq:
    host: 123.206.255.244
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /rabbit-1
    publisher-confirms: true
    publisher-returns: true
    listener:
        simple:
          prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@47.94.235.82:7776/eureka/